import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  Box,
  CssBaseline,
  ScopedCssBaseline,
  ThemeProvider,
} from "@mui/material";
import Header from "@/components/layout/Header";
import theme from "../../theme.config";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <html lang="fa">
        <body>
          <Box sx={{ backgroundColor: "#eeeeee" }}>
            <Header />
            <Box>{children}</Box>
            <Footer />
          </Box>
        </body>
      </html>
    </ThemeProvider>
  );
}
