export const productsData = [
  {
    id: 1,
    name: "iphone14",
    price: "5,750,000",
    image: "iphone--14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 1,
    Popularity: 1,
    discountPercentage: "",
    colors: ["آبی", "صورتی"],
  },
  {
    id: 2,
    name: "مچ بند شیائومی",
    price: "6,130,000",
    image: "MiBand8.jpg",
    brand: "شیائومی",
    type: "watch",
    saleNumber: 1,
    Popularity: 2,
    discountPercentage: "5",
    colors: ["قرمز", "نارنجی", "آبی"],
  },
  {
    id: 3,
    name: "MacBook Pro",
    price: "7,250,000",
    image: "MacBookProMNWA32023.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 1,
    Popularity: 3,
    discountPercentage: "",
    colors: ["سبز"],
  },
  {
    id: 4,
    name: "Redmi Note",
    price: "8,000,000",
    image: "redmeNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 2,
    Popularity: 4,
    discountPercentage: "14",
    colors: ["قرمز", "سبز", "آبی", "صورتی"],
  },
  {
    id: 5,
    name: "ساعت K59pro",
    price: "9,000,000",
    image: "K59pro.jpg",
    brand: "ایسوس",
    type: "watch",
    saleNumber: 2,
    Popularity: 5,
    discountPercentage: "",
    colors: ["قرمز", "نارنجی", "آبی"],
  },
  {
    id: 6,
    name: " MGN63 2020",
    price: "10,000,000",
    image: "MacBookAirMGN632020.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 2,
    Popularity: 6,
    discountPercentage: "24",
    colors: ["قرمز", "نارنجی"],
  },
  {
    id: 7,
    name: "Galaxy A14",
    price: "11,000,000",
    image: "galaxyA14.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 3,
    Popularity: 7,
    discountPercentage: "",
    colors: ["قرمز", "نارنجی", "زرد", "صورتی"],
  },
  {
    id: 8,
    name: " مدل T500",
    price: "12,000,000",
    image: "T500.jpg",
    brand: "اپل",
    type: "watch",
    saleNumber: 3,
    Popularity: 8,
    discountPercentage: "5",
    colors: ["قرمز"],
  },
  {
    id: 9,
    name: "MacBook 2022",
    price: "13,000,000",
    image: "MacBookAir-BM22022.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 3,
    Popularity: 9,
    discountPercentage: "",
    colors: ["زرد", "صورتی"],
  },
  {
    id: 10,
    name: "Y9a",
    price: "14,000,000",
    image: "Y9a.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 4,
    Popularity: 10,
    discountPercentage: "2",
    colors: ["قرمز", "نارنجی", "صورتی"],
  },
  {
    id: 11,
    name: "Vivobook",
    price: "15,000,000",
    image: "Vivobook15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 4,
    Popularity: 11,
    discountPercentage: "",
    colors: ["سبز", "آبی"],
  },
  {
    id: 12,
    name: "iphone15",
    price: "16,000,000",
    image: "galaxyA14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 5,
    Popularity: 12,
    discountPercentage: "7",
    colors: ["قرمز", "نارنجی", "زرد"],
  },
  {
    id: 13,
    name: "Gaming F15",
    price: "17,000,000",
    image: "TUFGamingF15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 5,
    Popularity: 13,
    discountPercentage: "",
    colors: ["آبی", "صورتی"],
  },
  {
    id: 14,
    name: "Pro Plus 5G",
    price: "18,000,000",
    image: "redmiNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 6,
    Popularity: 14,
    discountPercentage: "25",
    colors: ["قرمز", "نارنجی", "زرد", "سبز"],
  },
  {
    id: 15,
    name: "Galaxy S23",
    price: "19,000,000",
    image: "galaxyS23.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 7,
    Popularity: 15,
    discountPercentage: "",
    colors: ["قرمز", "نارنجی", "زرد"],
  },
  {
    id: 16,
    name: "Nova 11i",
    price: "20,000,000",
    image: "Nova11i.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 8,
    Popularity: 16,
    discountPercentage: "12",
    colors: ["زرد", "سبز"],
  },
];
